### ISSUE TITLE
Slot lists issue

### ISSUE THREAD

**Issue by JaviElio** [synesthesiam/rhasspy-hassio-addon#128]
Slot lists do not work when entries begin or contain capital letter as the documentation example.

This works:
 "room": [ "living", "kitchen"],

This do not work:
"room": ["Living", "Kitchen"],

**Comment by synesthesiam** [comment]
I have a fix in `master` that will force slot values to the proper casing. I'll be pushing a Docker image for this later today.

**Comment by lukastillmann** [comment]
This might not exactly fit here, but what is the proper casing? Do all slots have to be lower case?

I'm wondering if it is possible to send upper or mixed case slot values to Home Assistant

**Comment by synesthesiam** [comment]
Slot values will currently all get lower-cased because the pronunciation dictionaries for the speech systems in Rhasspy contain lower-cased words.

I think it make it so mixed case will work, I'll have to actually encode words that aren't lower cased as substitutions and do case-insensitive matching during intent recognition. For now, I've taken the lazier approach and forced all words to match the dictionary :/

**Comment by synesthesiam** [comment]
See: https://community.rhasspy.org/t/slot-synonyms-upper-and-lower-case/361
