### ISSUE TITLE
Self-signed SSL Cert on Home Assistant instance prevents Rhasspy from connecting

### ISSUE THREAD

**Issue by troytc** [synesthesiam/rhasspy-hassio-addon#5]
If your HA instance is secured with a self-signed SSL cert (as mine is) then rhasspy will throw an error when you ask it to parse an intent and send it to Home Assistant:

`HTTPSConnectionPool(host='home-assistant.local', port=443): Max retries exceeded with url: /api/events/rhasspy_ChangeInput (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) `

**Comment by synesthesiam** [comment]
OK, thank you. It looks like the `requests` library just [needs access to your .pem file](https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate).

I've added a [new profile option](https://rhasspy.readthedocs.io/en/latest/intent-handling/#self-signed-certificate) for this purpose. Set `home_assistant.pem_file` to your <a href="http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification">CA_BUNDLE file or a directory with certificates of trusted CAs</a>. You can also access it through the Settings page.

If you put the .pem file inside your profile directory, you can use something like `$RHASSPY_PROFILE_DIR/my.pem` instead of the full path.

Let me know if this works, since I don't have a self-signed certificate on my Home Assistant :)

**Comment by troytc** [comment]
Works perfectly :) Thanks for the quick fix!
