### ISSUE TITLE
One intent overrules all the others

### ISSUE THREAD

**Issue by mathquis** [synesthesiam/rhasspy-hassio-addon#58]
Some of my intents are more complex than others (multiple slots, lots of variations) and seem to override the others.

Ex (not the real one because my language is french and my intents are more complex) :
```
[onPlay]
play music

[onAlarm]
create ( an alarm | a timer | a reminder | ... ) for ( ...multiple datetime variation... ) with music from ( ...lots of artist... )
```

When I try to recognize a WAV file with `play music` I get `create ...`
If I remove the `onAlarm` intent I get the correct result.

This is probably due to the language model (N-grams) increasing the likelihood of the `create` word.

Is there something that can be done to avoid having words that completely override others (a limiting factor maybe? some weighting calculation between intents?)

**Comment by synesthesiam** [comment]
Yes, the problem is exactly what you suspect: n-gram counts are biased towards intents with more possible sentences. I've had this problem since I moved away from generating all possible sentences up front.

The solution should be to modify the initial transition weights in `intent.fst` that represent each intent (they're labelled with `__label__<INTENT_NAME>`.  I assume the weight will be picked up by the `opengrm` toolkit down the line and reflect correctly in the ARPA probabilities.

This is definitely a high priority bug as folks with more complex intents start using Rhasspy!

**Comment by mathquis** [comment]
Using the GrammarFst system should also radicaly reduce the number of possible sentences and help with this issue :)

**Comment by synesthesiam** [comment]
Intents should now be balanced!

**Comment by mathquis** [comment]
I pulled `rhasspy-server:latest` but I'm still getting incorrect ASR recognition for intents.

If I reduce the number of variations on a particular intent (one that have a `( <duration> | <datatime> )` ), everything starts to work fine again.

Most of the variations are coming from these "rule based slots" (`datetime`, `number`, `duration`, etc.) but can also come from big custom slots (artist names, song tracks, etc.).

I'm unfortunately not able to provide a simple example since my intents are pretty complex (and in french). I can send you my sentences.ini and slots if you want.

Hope this helps.
