### ISSUE TITLE
Dowload-dependencies.sh gives a vague error when URL not found

### ISSUE THREAD

**Issue by koenvervloesem** [synesthesiam/rhasspy-hassio-addon#65]
I get this on Ubuntu 19.10:

```
$ ./download-dependencies.sh 
curl: (22) The requested URL returned error: 404 Not Found
```
I don't know which URL it doesn't find. Is it possible to give a more descriptive error message with the URL that isn't found?

**Comment by koenvervloesem** [comment]
Adding `-v` to the curl command in the function `maybe_download` shows that it's about this URL:

https://github.com/synesthesiam/rhasspy/releases/download/v2.0/rhasspy-tools_amd64.tar.gz

Indeed, it doesn't exist in the 2.0 release assets:

- rhasspy-tools_aarch64.tar.gz
- rhasspy-tools_arm64.tar.gz
- rhasspy-tools_armhf.tar.gz
- rhasspy-web-dist.tar.gz
- Source code (zip)
- Source code (tar.gz)

But shouldn't the download script refer to the 2.4 release?

**Comment by 76MPaul** [comment]
Hi, 

I spent my whole day getting out of this.
I modify the download-dependency.sh 

` ---Rhasspy ---

echo "starting Rhasspy downloads"

for FRIENDLY_ARCH in "${FRIENDLY_ARCHS[@]}"; do
    rhasspy_files=("rhasspy-server_2.4.10_amd64.deb")
    for rhasspy_file_name in "${rhasspy_files[@]}"; do
        rhasspy_file="${download_dir}/${rhasspy_file_name}"
        rhasspy_file_url="https://github.com/synesthesiam/rhasspy/releases/download/v2.4/${rhasspy_$
        echo rhasspy_file_url
        echo "https://github.com/synesthesiam/rhasspy/releases/download/v2.4/${rhasspy_file_name}"
        maybe_download "${rhasspy_file_url}" "${rhasspy_file}"
    done
done`

Then you have to modify the create-venv.sh cause some dependencies are broken.
I was forced to add `--system-site-packages` to the venv creation in order to install all packages "by hand" in my server (like openfst that can't be install easily from within the virtual env). 

And lastly i modify the following part to install the .deb.
`# Extract Rhasspy tools
rhasspy_tools_file="${download_dir}/rhasspy-server_2.4.10_amd64.deb"
echo "Extracting tools (${rhasspy_tools_file})"
dpkg -i "${rhasspy_tools_file}" #-C "${venv}" -xf "${rhasspy_tools_file}"`

Hopping that will help, 

76MPaul

**Comment by synesthesiam** [comment]
I messed up and re-named the `amd64` to `arm64` 🤦‍♂  I've renamed it back, so hopefully the download script will work again. Sorry!

Depending on whose asking, it seems `arm64` is either called that, `aarch64`, or `arm64v8`. Different tools seems to require different names, so I'm failing to keep it consistent across my build pipeline. Too many manual steps.

**Comment by koenvervloesem** [comment]
It's working now.
