### ISSUE TITLE
Question: How does this project compare to "Project Alice"?

### ISSUE THREAD

**Issue by geotom** [synesthesiam/rhasspy-hassio-addon#76]
I'm coming from Snips and looking for a future project to use with my multi-site (PiZero) assistants and stumbled upon rhasspy and [Project Alice](https://github.com/project-alice-assistant/ProjectAlice). While I see that you have implemented the satellite communication according to Snips [hermes audio server protocol](https://github.com/koenvervloesem/hermes-audio-server), Alice seems to use its own protocol and advertises advanced features over hermes satellite communication. There is even [another Snips compatible audio-server named](https://github.com/Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer). Really curious what are the limitations using the hermes protocol and what sets your projects apart? I would also like to raise question, if it wouldn't be a good approach to streamline certain aspects between the two projects (like using similar communication protocols). This would ensure interoperability and allows users to switch systems or replace parts of them more easily.

**Comment by synesthesiam** [comment]
@maxbachmann could probably give more insight, since I believe he worked some on Project Alice. At this point, Rhasspy aims to provide implementations for all of the Snips core services. Additionally, Rhasspy is set apart by being completely offline (no console, etc.), and by supporting a larger number of languages. This comes at a cost, since Rhasspy's performance is not comparable yet to Snips.
